version: "3"

services:
  apache:
    image: luokeychen/msol-apache:1.0
    ports:
      - 8123:80
    volumes:
      - ./docker_files/apache/htdocs/:/usr/local/apache2/htdocs/
      - ./docker_files/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./movabletype/:/usr/local/apache2/cgi-bin/mt/
      - ./movabletype/mt-static/:/usr/local/apache2/htdocs/mt-static/
      - ./plugins/:/usr/local/src/plugins/
  mysql:
    image: luokeychen/msol-mysql:1.0
    environment:
      MYSQL_ROOT_PASSWORD: msolchina
      MYSQL_USER: admin
      MYSQL_PASSWORD: msolchina
      MYSQL_DATABASE: mt
      TZ: "Asia/Tokyo"
    ports:
      - 13306:3306
    volumes:
      - ./docker_files/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./docker_files/mysql/mysql_data:/var/lib/mysql
    tty: true
    stdin_open: true
  mailhog:
    image: luokeychen/msol-mailhog:1.0
    ports:
      - 8025:8025
  memcached:
    image: luokeychen/msol-memcached:1.0   
    ports:
      - 11211:11211
